/* English presentation for legacy system metadata. Never apply to user content. */
const uiText = (() => {
  const legacy = new Map([
    ["LLM 주소 또는 외부 전송 허용 설정을 확인하세요. 근거·지식 검색은 이용할 수 있습니다.", "Check the LLM URL and external transmission settings. Evidence and knowledge search remain available."],
    ["LLM에 연결하거나 인증할 수 없어 근거·지식 검색으로 전환했습니다. 모델 설정과 연결을 확인한 뒤 서버를 다시 시작하세요.", "Switched to evidence and knowledge search because the LLM could not connect or authenticate. Check the model settings and connection, then restart the server."],
    ["LLM 응답 형식을 사용할 수 없어 근거·지식 검색으로 전환했습니다. 모델 설정을 확인한 뒤 서버를 다시 시작하세요.", "Switched to evidence and knowledge search because the LLM response format is unsupported. Check the model settings, then restart the server."],
    ["현재 볼트의 일부 노트를 바탕으로 만든 질문입니다. 답변 가능 여부는 검색 후 확인합니다.", "Questions based on a sample of notes in the current vault. Whether they can be answered is checked after retrieval."],
    ["노트 제목으로 만든 기본 질문입니다. 모델 생성은 모델 설정과 전송 허용이 필요합니다.", "Basic questions based on note titles. Generated suggestions require a model and transmission permission."],
    ["영역은 제목·태그·명시 속성으로 분류합니다. 미분류 기록은 전체 범위에서 찾으세요.", "Domains are classified using titles, tags, and explicit properties. Use All records to find unclassified notes."],
    ["Finder 폴더 선택은 macOS에서 지원합니다. 폴더 경로를 직접 입력하세요.", "Finder folder selection is available on macOS. Enter the folder path manually."],
    ["규칙으로 명시 날짜만 비교했습니다. 의미적 충돌 점검은 생성 모델이 필요합니다.", "Only explicit dates were compared using rules. Semantic conflict checks require a generation model."],
    ["폴더 선택 창을 열지 못했습니다. 경로를 직접 입력하거나 다시 시도하세요.", "Could not open the folder selection window. Enter the path manually or try again."],
    ["이미 폴더 선택 창이 열려 있습니다. 해당 창에서 선택하거나 취소하세요.", "A folder selection window is already open. Choose a folder or cancel in that window."],
    ["폴더 선택 시간이 만료되었습니다. Finder로 선택을 다시 눌러주세요.", "Folder selection timed out. Choose the Finder option again."],
    ["예상 질문을 만들 본문이 없습니다. 제외 규칙과 색인 상태를 확인하세요.", "No source text is available for suggested questions. Check exclusions and index status."],
    ["인용은 당시 기록입니다. 현재 사실·보유·실제 매매로 추정하지 않습니다.", "Citations reflect records from that time, not verified current facts, holdings, or completed trades."],
    ["LLM에 연결하거나 인증할 수 없어 근거·지식 검색으로 전환했습니다. ", "Switched to evidence and knowledge search because the LLM could not connect or authenticate. "],
    ["LLM 응답 형식을 사용할 수 없어 근거·지식 검색으로 전환했습니다. ", "Switched to evidence and knowledge search because the LLM response format is unsupported. "],
    ["기간은 기록일 기준입니다. 날짜 미상 기록은 기간 검색에서 제외됩니다.", "Date filters use recorded dates. Undated records are excluded from date-filtered searches."],
    ["외부 모델 전송이 허용되지 않았습니다. 별도 환경변수로 허용하세요.", "External model transmission is disabled. Enable it with the corresponding environment variable."],
    ["LLM 주소와 모델이 설정되지 않아 근거·지식 검색으로 이용합니다.", "No LLM URL and model are configured. Evidence and knowledge search are available."],
    ["확인을 보류한 쟁점은 결론을 선택하지 않고 원문을 함께 표시합니다.", "Deferred questions show both source records without choosing a conclusion."],
    ["진행·확인 대기 작업은 최대 8개입니다. 기존 작업을 마쳐주세요.", "Up to 8 questions can be active or awaiting confirmation. Finish an existing question first."],
    ["근거가 바뀌어 이전 선택을 적용하지 않았습니다. 다시 질문하세요.", "The evidence changed, so your earlier choice was not applied. Please ask again."],
    ["예상 질문 생성에 실패해 노트 제목으로 기본 질문을 만들었습니다.", "Question generation failed. Basic questions were prepared from note titles instead."],
    ["처리 중 노트가 다시 바뀌었습니다. 최신 버전을 다시 색인합니다.", "The note changed during processing. Its latest version will be indexed again."],
    ["LLM API 키가 설정되지 않아 근거·지식 검색으로 이용합니다.", "No LLM API key is configured. Evidence and knowledge search are available."],
    ["의미적 충돌 점검에 실패했습니다. 충돌이 없다는 뜻은 아닙니다.", "The semantic conflict check failed. This does not mean there are no conflicts."],
    ["선택한 폴더를 찾을 수 없습니다. 폴더 위치를 다시 확인하세요.", "The selected folder was not found. Check its location."],
    ["폴더 선택을 사용할 수 없습니다. 폴더 경로를 직접 입력하세요.", "Folder selection is unavailable. Enter the folder path manually."],
    ["파일 변경 감시가 중단되었습니다. 메타데이터를 다시 확인합니다.", "File watching stopped. File metadata will be checked again."],
    ["다운로드 대기: iCloud 파일을 다운로드 유지로 설정하세요.", "Download pending: set the iCloud file to Keep Downloaded."],
    ["로컬 임베딩은 현재 기본 다국어 MiniLM 모델을 지원합니다.", "Local embeddings currently support the default multilingual MiniLM model."],
    ["색인 폴더는 iCloud·클라우드 동기화 폴더 밖이어야 합니다.", "The index folder must be outside iCloud and other cloud-synced folders."],
    ["처리 중 근거가 바뀌었습니다. 최신 색인에서 다시 질문하세요.", "The evidence changed during processing. Ask again using the latest index."],
    ["frontmatter YAML 별칭 참조는 지원하지 않습니다.", "YAML aliases in frontmatter are not supported."],
    ["답변 생성 또는 인용 검증에 실패해 원문 근거를 표시합니다.", "Answer generation or citation validation failed. Showing source evidence instead."],
    ["답변 기준을 확인해주세요. 원문 두 곳을 함께 표시합니다.", "Please confirm how to interpret these two source passages."],
    ["같은 기록일의 날짜가 다릅니다. 사건·조건을 확인해주세요.", "Records with the same recorded date contain different dates. Check the event and conditions."],
    ["로컬 임베딩 모델을 준비하면 의미 검색이 함께 동작합니다.", "Prepare the local embedding model to enable semantic search."],
    ["이 볼트에서 물어볼 만한 예상 질문을 최대 6개 제안해줘.", "Suggest up to 6 useful questions to ask about this vault."],
    ["다른 볼트를 연결하려면 기존 로컬 색인을 먼저 삭제하세요.", "Delete the current local index before connecting a different vault."],
    ["제외 경로는 볼트 안의 상대 경로 또는 패턴이어야 합니다.", "Excluded paths must be relative paths or patterns inside the vault."],
    ["원문이 변경되었습니다. 색인이 갱신된 뒤 다시 확인하세요.", "The source text changed. Check again after the index is updated."],
    ["모델 주소는 인증정보 없는 HTTP(S) 주소여야 합니다.", "The model URL must use HTTP(S) and must not contain credentials."],
    ["확인 내용을 저장했습니다. 근거를 재확인하고 이어갑니다.", "Your confirmation was saved. Rechecking the evidence before continuing."],
    ["생성 중 바뀐 노트를 제외하고 기본 질문을 만들었습니다.", "Basic questions were prepared, excluding notes that changed during generation."],
    ["실행 중인 요청이 많습니다. 잠시 후 다시 질문하세요.", "Too many requests are running. Please try again shortly."],
    ["같은 요청 ID로 다른 확인 내용을 보낼 수 없습니다.", "A request ID cannot be reused for a different confirmation."],
    ["검증된 근거와 확인 내용을 바탕으로 답변을 작성합니다.", "Writing an answer using verified evidence and your confirmations."],
    ["LLM 주소 또는 외부 전송 허용 설정을 확인하세요. ", "Check the LLM URL and external transmission settings. "],
    ["모델 설정과 연결을 확인한 뒤 서버를 다시 시작하세요.", "Check the model settings and connection, then restart the server."],
    ["질문을 취소했습니다. 늦게 도착한 응답은 폐기합니다.", "Question cancelled. Any late response will be discarded."],
    ["같은 색인 폴더를 사용하는 앱이 이미 실행 중입니다.", "Another app instance is already using this index folder."],
    ["현재 볼트의 일부 노트를 바탕으로 만든 질문입니다. ", "Questions based on a sample of notes in the current vault. "],
    ["iCloud 다운로드 대기: 로컬에 파일이 없습니다.", "Waiting for iCloud download: the file is not available locally."],
    ["frontmatter는 64 KiB 이하여야 합니다.", "Frontmatter must be no larger than 64 KiB."],
    ["다른 사이트에서는 로컬 데이터에 접근할 수 없습니다.", "Other websites cannot access this app's local data."],
    ["확인 질문이 바뀌었습니다. 최신 질문을 확인하세요.", "The clarification question has changed. Review the latest question."],
    ["문장별 인용과 원문의 현재 버전을 다시 확인합니다.", "Rechecking sentence citations and the current source versions."],
    ["문단 구조가 바뀌었습니다. 정밀 검사를 실행하세요.", "The passage structure changed. Run a deep scan."],
    ["같은 요청 ID로 다른 질문을 보낼 수 없습니다.", "A request ID cannot be reused for a different question."],
    ["확인한 근거가 바뀌어 답변을 게시하지 않았습니다.", "The verified evidence changed, so the answer was not published."],
    ["모델 요청이 많습니다. 잠시 후 다시 시도하세요.", "Too many model requests are running. Please try again shortly."],
    ["frontmatter YAML 형식을 확인하세요.", "Check the frontmatter YAML syntax."],
    ["변경 중이거나 읽을 수 없는 근거를 제외했습니다.", "Evidence that changed or could not be read was excluded."],
    ["서버 재시작으로 중단됐습니다. 다시 질문하세요.", "Interrupted by a server restart. Please ask again."],
    ["일반 Markdown 파일만 읽을 수 있습니다.", "Only regular Markdown files can be read."],
    ["근거가 변경되었습니다. 후보를 다시 생성하세요.", "The evidence changed. Generate the candidates again."],
    ["모델 응답 크기 또는 형식이 올바르지 않습니다.", "Invalid model response size or format."],
    ["모델 설정을 확인한 뒤 서버를 다시 시작하세요.", "Check the model settings, then restart the server."],
    ["노트의 한 줄은 16,384자 이하여야 합니다.", "Each line in a note must be no longer than 16,384 characters."],
    ["frontmatter의 닫는 ---가 없습니다.", "Frontmatter is missing its closing --- delimiter."],
    ["이 대화의 진행 중인 질문을 먼저 마쳐주세요.", "Finish the active question in this conversation first."],
    ["검색된 원문 근거와 지식 그래프를 정리합니다.", "Preparing the retrieved source evidence and knowledge graph."],
    ["의미 검색에 실패해 단어 검색을 사용했습니다.", "Semantic search failed. Keyword search was used instead."],
    ["볼트 설정이 바뀌어 관계 제안을 폐기했습니다.", "The vault settings changed, so the relationship suggestions were discarded."],
    ["frontmatter 구조가 너무 복잡합니다.", "The frontmatter structure is too complex."],
    ["frontmatter는 속성 객체여야 합니다.", "Frontmatter must be a mapping of properties."],
    ["기간 전체를 빠짐없이 요약한 결과는 아닙니다.", "This is not a complete summary of every record in the selected period."],
    ["작업 상태가 바뀌었습니다. 새로 확인하세요.", "The task status has changed. Refresh and try again."],
    ["작업을 마치지 못했습니다. 다시 질문하세요.", "The task could not be completed. Please ask again."],
    ["현재 볼트에서 예상 질문을 만들고 있습니다.", "Preparing suggested questions from the current vault."],
    ["노트 한 개는 8 MiB 이하여야 합니다.", "Each note must be no larger than 8 MiB."],
    ["외부 모델은 HTTPS 주소를 사용하세요.", "External models must use an HTTPS URL."],
    ["임베딩 차원 또는 값이 올바르지 않습니다.", "Invalid embedding dimensions or values."],
    ["볼트 설정이 바뀌어 작업을 취소했습니다.", "The task was cancelled because the vault settings changed."],
    ["검색된 문단의 원문과 버전을 확인합니다.", "Checking the original text and version of the retrieved passages."],
    ["시점·조건과 상충하는 기록을 비교합니다.", "Comparing records for differences in dates, conditions, and claims."],
    ["원문 근거와 지식 그래프를 저장했습니다.", "Source evidence and knowledge graph saved."],
    ["출처를 확인할 수 없는 생성 문장입니다.", "A generated sentence has an unverifiable citation."],
    ["관계의 출처 구조 검증에 실패했습니다: ", "Relationship provenance validation failed: "],
    ["예상 질문의 근거를 확인할 수 없습니다.", "The suggested question's evidence could not be verified."],
    ["로컬 의미 검색 모델을 먼저 준비하세요.", "Prepare the local semantic search model first."],
    ["날짜는 YYYY-MM-DD로 입력하세요.", "Enter dates in YYYY-MM-DD format."],
    ["현재 응답을 기다리는 작업이 아닙니다.", "This task is not awaiting a response."],
    ["Obsidian 볼트 폴더를 선택하세요", "Choose your Obsidian vault folder"],
    ["답변 가능 여부는 검색 후 확인합니다.", "Whether they can be answered is checked after retrieval."],
    ["파일 교체 중입니다. 다시 확인합니다.", "The file is being replaced. It will be checked again."],
    ["파일 저장 중입니다. 다시 확인합니다.", "The file is being saved. It will be checked again."],
    ["존재하는 볼트 폴더 경로를 입력하세요.", "Enter the path to an existing vault folder."],
    ["근거·지식 검색은 이용할 수 있습니다.", "Evidence and knowledge search remain available."],
    ["질문 범위에 맞는 근거를 검색합니다.", "Searching for evidence within the question's scope."],
    ["관계 후보 형식이 올바르지 않습니다.", "Invalid relationship candidate format."],
    ["색인 완료 후 예상 질문을 만듭니다.", "Suggested questions will be prepared after indexing."],
    ["예상 질문 형식이 올바르지 않습니다.", "Invalid suggested question format."],
    ["예상 질문 길이가 올바르지 않습니다.", "Invalid suggested question length."],
    ["볼트 밖의 경로는 읽을 수 없습니다.", "Paths outside the vault cannot be read."],
    ["요청은 64 KiB 이하여야 합니다.", "Requests must be no larger than 64 KiB."],
    ["볼트 안의 파일 경로를 입력하세요.", "Enter a file path inside the vault."],
    ["벡터 갱신 중 원문이 바뀌었습니다.", "The source text changed during the vector update."],
    ["모델에 전달할 근거가 너무 큽니다.", "The evidence is too large to send to the model."],
    ["색인 폴더는 볼트 밖이어야 합니다.", "The index folder must be outside the vault."],
    ["이벤트 번호가 올바르지 않습니다.", "Invalid event number."],
    ["심볼릭 링크는 색인하지 않습니다.", "Symbolic links are not indexed."],
    ["이 앱 화면에서 다시 요청하세요.", "Send this request again from the app."],
    ["작업 또는 기록이 삭제되었습니다.", "The task or record was deleted."],
    ["질문에 답할 근거가 부족합니다.", "There is not enough evidence to answer this question."],
    ["근거 비교 결과를 확인합니다.", "Reviewing the evidence comparison."],
    ["질문 대상이 원문에 없습니다.", "The question's subject is not present in the source text."],
    ["시작일이 종료일보다 늦습니다.", "The start date is later than the end date."],
    ["확인한 근거를 재검증합니다.", "Revalidating the confirmed evidence."],
    ["답변과 근거를 저장했습니다.", "Answer and evidence saved."],
    ["열린 진행 연결이 많습니다.", "Too many progress connections are open."],
    ["질문 실행 기록이 없습니다.", "Question run not found."],
    ["볼트에 접근할 수 없습니다.", "The vault could not be accessed."],
    ["이 앱 화면에서 요청하세요.", "Send this request from the app."],
    ["충돌 가능성 · 확인 필요", "Possible conflict · confirmation needed"],
    ["아직 색인하지 않았습니다.", "Not indexed yet."],
    ["기록에서 찾은 근거입니다.", "Evidence found in your notes."],
    ["먼저 볼트를 연결하세요.", "Connect a vault first."],
    ["확인 내용을 입력하세요.", "Enter your confirmation."],
    ["질문 작업이 없습니다.", "Question task not found."],
    ["대화 기록이 없습니다.", "Conversation not found."],
    ["질문 기록이 없습니다.", "Question history not found."],
    ["질문을 접수했습니다.", "Question received."],
    ["의미 검색 벡터 없음", "No semantic search vector is available."],
    ["로컬 모델 준비 중", "Preparing local model"],
    ["질문을 입력하세요.", "Enter a question."],
    ["사용자 확인 기록", "User confirmation"],
    ["같은 노트 맥락", "Same-note context"],
    ["색인 갱신 중", "Updating index"],
    ["정밀 검사 중", "Deep scan in progress"],
    ["제외된 근거", "Excluded evidence"],
    ["판단 보류", "Decision deferred"],
    ["원문 변경", "Source text changed"],
    ["기록일", "Recorded date"],
    ["단어", "Keyword"],
    ["의미", "Semantic"],
    ["관계", "Relationship"],
  ]);
  return value => {
    if (typeof value !== 'string') return value;
    if (legacy.has(value)) return legacy.get(value);
    let text = value
      .replace(/검증된 (\d+)개 문단을 표시합니다\. 갱신·오류 노트 (\d+)개\. /g, 'Showing $1 verified passages; $2 notes are pending or have errors. ')
      .replace(/의미 검색을 사용할 수 없어 단어 검색을 사용했습니다 \(([^)]+)\)\./g, 'Semantic search is unavailable; keyword search was used instead ($1).')
      .replace(/의미 색인 대기: /g, 'Semantic indexing pending: ');
    for (const [source, english] of legacy) {
      // Short route names are exact-match only; longer messages may be concatenated.
      if (source.length > 8) text = text.replaceAll(source, english);
    }
    return text;
  };
})();
if (typeof module !== 'undefined') module.exports = uiText;
